### ISSUE TITLE
http或者https下发起视频报找不到摄像头麦克风

### ISSUE THREAD

**Issue by milesking** [comsince/universe_push#4]
Hi,
我在访问https://www.comsince.cn/chat/index.html或者是本地跑起来的http://localhost:8080。浏览器都会报这样的一个错Unable to open your call because no camera and/or microphonewere found.
其中本地由于是http无法给url开摄像头和麦克风权限，但是demo的https链接都直接允许了麦克风和摄像头权限。
系统Mac OS Catalina，浏览器Chrome81.0.4044.122，最新版本的firefox和Safari也都是发起语音就报错。能麻烦指点一下吗，多谢。

**Comment by comsince** [comment]
mac os 最新版本的chrome也不行？另外有问题，你可以到chat.comsince.cn这里找我，演示帐号138系列帐号也可以登录

**Comment by milesking** [comment]
> mac os 最新版本的chrome也不行？另外有问题，你可以到chat.comsince.cn这里找我，演示帐号138系列帐号也可以登录

不好意思是我自己的问题：本地问题的原因是需要用localhost访问，chat.comsince.cn的原因是我没有摄像头，在笔记本上发起呼叫是可以的。不过仅发起语音呼叫好像也会开启摄像头。
